// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace test2.Migrations
{
    [DbContext(typeof(QuizContext))]
    partial class QuizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.QuizDetail", b =>
                {
                    b.Property<int>("QId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sourcename")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("choices1")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("choices2")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("choices3")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("choices4")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("choices5")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("docurl")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("imageurl")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.HasKey("QId");

                    b.ToTable("QuizDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
